/**
 * Downloadable PDF assets in /public/downloads/.
 * Register files here after adding them to the folder.
 */

import { IR_DOCUMENT_COVERS } from '@/lib/content/photography';
import { enrichDownloadDocument } from '@/lib/investor/document-filters';
import type { DownloadDocument } from '@/types';

export interface DocumentAsset {
  id: string;
  path: string;
  filename: string;
  fileSize: string;
  category: string;
  year: number;
  language: 'en' | 'th' | 'pt-br' | 'all';
  title: string;
  gated?: boolean;
  coverImage?: string;
  featured?: boolean;
}

const IR_COVER = IR_DOCUMENT_COVERS.default;
const ANNUAL_COVER = IR_DOCUMENT_COVERS.annual;
const ESG_COVER = IR_DOCUMENT_COVERS.esg;

/** Curated registry — maps site download entries to files in public/downloads/ */
export const DOCUMENT_ASSETS: DocumentAsset[] = [
  // —— Annual reports ——
  {
    id: 'annual-report-2024-25',
    path: '/downloads/annual-report-2024-25.pdf',
    filename: 'annual-report-2024-25.pdf',
    fileSize: '5.8 MB',
    category: 'annual-report',
    year: 2025,
    language: 'en',
    title: 'Annual Report 2024/25',
    coverImage: ANNUAL_COVER,
    gated: true,
    featured: true,
  },
  {
    id: 'annual-report-2022-23',
    path: '/downloads/2022-23-annual-report-1.pdf',
    filename: '2022-23-annual-report-1.pdf',
    fileSize: '2.2 MB',
    category: 'annual-report',
    year: 2023,
    language: 'en',
    title: 'Annual Report 2022/23',
    coverImage: ANNUAL_COVER,
    gated: true,
  },
  {
    id: 'annual-report-2022',
    path: '/downloads/2022-annual-report-web.pdf',
    filename: '2022-annual-report-web.pdf',
    fileSize: '1.3 MB',
    category: 'annual-report',
    year: 2022,
    language: 'en',
    title: 'Annual Report 2022',
    coverImage: ANNUAL_COVER,
  },
  {
    id: 'annual-report-2018-19',
    path: '/downloads/annual-report-18-19.pdf',
    filename: 'annual-report-18-19.pdf',
    fileSize: '1.9 MB',
    category: 'annual-report',
    year: 2019,
    language: 'en',
    title: 'Annual Report 2018/19',
    coverImage: ANNUAL_COVER,
  },

  // —— Sustainability & NFS ——
  {
    id: 'non-financial-statement-2024-25',
    path: '/downloads/non-financial-statement-2024-25.pdf',
    filename: 'non-financial-statement-2024-25.pdf',
    fileSize: '7.0 MB',
    category: 'sustainability-report',
    year: 2025,
    language: 'all',
    title: 'Non-Financial Statement 2024/25',
    coverImage: ESG_COVER,
    featured: true,
  },
  {
    id: 'sustainability-report-2024',
    path: '/downloads/memoria-sostenibilidad-2024.pdf',
    filename: 'memoria-sostenibilidad-2024.pdf',
    fileSize: '18.1 MB',
    category: 'sustainability-report',
    year: 2024,
    language: 'all',
    title: 'Sustainability Report 2024 (Iberia)',
    coverImage: ESG_COVER,
  },
  {
    id: 'sustainability-report-2023',
    path: '/downloads/memoria-sostenibilidad-2023.pdf',
    filename: 'memoria-sostenibilidad-2023.pdf',
    fileSize: '6.6 MB',
    category: 'sustainability-report',
    year: 2023,
    language: 'all',
    title: 'Sustainability Report 2023 (Iberia)',
    coverImage: ESG_COVER,
  },
  {
    id: 'sustain-2030-leaflet',
    path: '/downloads/sustain-2030-leaflet-en.pdf',
    filename: 'sustain-2030-leaflet-en.pdf',
    fileSize: '3.1 MB',
    category: 'brochure',
    year: 2025,
    language: 'en',
    title: "SUSTAIN'2030 — CSR Roadmap Leaflet",
    coverImage: ESG_COVER,
  },
  {
    id: 'ethical-charter-2025',
    path: '/downloads/ethical-charter-2025-tereos.pdf',
    filename: 'ethical-charter-2025-tereos.pdf',
    fileSize: '9.7 MB',
    category: 'brochure',
    year: 2025,
    language: 'all',
    title: 'Ethical Charter 2025',
    featured: true,
  },
  {
    id: 'quality-charter-2023',
    path: '/downloads/quality-charter-2023-eng.pdf',
    filename: 'quality-charter-2023-eng.pdf',
    fileSize: '407 KB',
    category: 'certification',
    year: 2023,
    language: 'en',
    title: 'Quality Charter 2023',
  },
  {
    id: 'sbti-flag-net-zero',
    path: '/downloads/cp-sbti-flag-net-zero-eng.pdf',
    filename: 'cp-sbti-flag-net-zero-eng.pdf',
    fileSize: '305 KB',
    category: 'brochure',
    year: 2024,
    language: 'en',
    title: 'SBTi FLAG Net Zero Commitment',
    coverImage: ESG_COVER,
  },

  // —— Investor presentations ——
  {
    id: 'presentation-fy-2019-20',
    path: '/downloads/tereos-2019-20-full-year-results-presentation-v2.pdf',
    filename: 'tereos-2019-20-full-year-results-presentation-v2.pdf',
    fileSize: '4.7 MB',
    category: 'presentation',
    year: 2020,
    language: 'en',
    title: 'Full Year 2019/20 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-fy-2019-20-eng',
    path: '/downloads/2020-06-03-tereos-presentation-annual-results-19-20-eng.pdf',
    filename: '2020-06-03-tereos-presentation-annual-results-19-20-eng.pdf',
    fileSize: '3.4 MB',
    category: 'presentation',
    year: 2020,
    language: 'en',
    title: 'Annual Results 2019/20 — Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-fy-2018-19',
    path: '/downloads/finance-fy-18-19-results-and-perspectives-presentation-eng-vf.pdf',
    filename: 'finance-fy-18-19-results-and-perspectives-presentation-eng-vf.pdf',
    fileSize: '2.9 MB',
    category: 'presentation',
    year: 2019,
    language: 'en',
    title: 'FY 2018/19 Results & Perspectives Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-fy-2017-18',
    path: '/downloads/tereos-group---2017-18-annual-results---investor-presentation---gb.pdf',
    filename: 'tereos-group---2017-18-annual-results---investor-presentation---gb.pdf',
    fileSize: '6.9 MB',
    category: 'presentation',
    year: 2018,
    language: 'en',
    title: 'FY 2017/18 Annual Results — Investor Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-h1-2016-17',
    path: '/downloads/h1-16-17-bondholders-results-presentation.pdf',
    filename: 'h1-16-17-bondholders-results-presentation.pdf',
    fileSize: '2.6 MB',
    category: 'presentation',
    year: 2017,
    language: 'en',
    title: 'H1 2016/17 Bondholders Results Presentation',
    coverImage: IR_COVER,
  },

  // —— IR documents & press releases ——
  {
    id: 'press-annual-results-2025-26',
    path: '/downloads/tereos-2025-26-financial-results-press-release.pdf',
    filename: 'tereos-2025-26-financial-results-press-release.pdf',
    fileSize: '1.3 MB',
    category: 'ir-document',
    year: 2026,
    language: 'en',
    title: 'Full Year 2025/26 Results — Press Release',
    coverImage: IR_COVER,
    featured: true,
  },
  {
    id: 'press-half-year-2025-26',
    path: '/downloads/20251121-pr-tereos-half-year-financial-results.pdf',
    filename: '20251121-pr-tereos-half-year-financial-results.pdf',
    fileSize: '1.0 MB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Half-Year Results 2025/26 — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-cdp-rating-2026',
    path: '/downloads/cp-tereos-cdp-rating.pdf',
    filename: 'cp-tereos-cdp-rating.pdf',
    fileSize: '582 KB',
    category: 'ir-document',
    year: 2026,
    language: 'en',
    title: 'CDP Climate & Water Ratings — Press Release',
  },
  {
    id: 'press-cogeca-award-2025',
    path: '/downloads/20251120-cp-tereos-cogeca-award.pdf',
    filename: '20251120-cp-tereos-cogeca-award.pdf',
    fileSize: '508 KB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Cultivate Net-Zero — European Award Press Release',
  },
  {
    id: 'press-saf-2026',
    path: '/downloads/pr-tereos-rebound-.pdf',
    filename: 'pr-tereos-rebound-.pdf',
    fileSize: '295 KB',
    category: 'ir-document',
    year: 2026,
    language: 'en',
    title: 'Sustainable Aviation Fuel Project — Press Release',
  },
  {
    id: 'financial-statements-2019-20',
    path: '/downloads/tereos-group-audited-consolidated-financial-statements-19-20.pdf',
    filename: 'tereos-group-audited-consolidated-financial-statements-19-20.pdf',
    fileSize: '2.0 MB',
    category: 'ir-document',
    year: 2020,
    language: 'en',
    title: 'Audited Consolidated Financial Statements 2019/20',
    coverImage: IR_COVER,
  },
  {
    id: 'press-net-zero-target',
    path: '/downloads/press-release-tereos-targets-net-zero-emissions-throughout-the-value-chain-final.pdf',
    filename: 'press-release-tereos-targets-net-zero-emissions-throughout-the-value-chain-final.pdf',
    fileSize: '322 KB',
    category: 'ir-document',
    year: 2021,
    language: 'en',
    title: 'Net Zero Emissions Target — Press Release',
  },

  // —— Corporate & product brochures ——
  {
    id: 'corporate-brochure-essentiel',
    path: '/downloads/tereos-essentiel2015-gb-hd.pdf',
    filename: 'tereos-essentiel2015-gb-hd.pdf',
    fileSize: '4.7 MB',
    category: 'brochure',
    year: 2015,
    language: 'en',
    title: 'Tereos Essentiel — Corporate Brochure',
    featured: true,
  },
  {
    id: 'product-actifiber',
    path: '/downloads/tereos-cp-actifiber-en.pdf',
    filename: 'tereos-cp-actifiber-en.pdf',
    fileSize: '432 KB',
    category: 'catalog',
    year: 2025,
    language: 'en',
    title: 'Actifiber® — Product Brochure',
  },

  // —— Additional library (full public/downloads batch) ——
  {
    id: 'annual-report-2024',
    path: '/downloads/annual-report-2024.pdf',
    filename: 'annual-report-2024.pdf',
    fileSize: '7.0 MB',
    category: 'annual-report',
    year: 2024,
    language: 'en',
    title: 'Annual Report 2024',
    coverImage: ANNUAL_COVER,
    gated: true,
  },
  {
    id: 'dpef-2020',
    path: '/downloads/200722-dpef-eng.pdf',
    filename: '200722-dpef-eng.pdf',
    fileSize: '1.4 MB',
    category: 'sustainability-report',
    year: 2020,
    language: 'en',
    title: 'DPEF / Non-Financial Statement 2020',
    coverImage: ESG_COVER,
  },
  {
    id: 'dpef-2021',
    path: '/downloads/dpef-2021-en.pdf',
    filename: 'dpef-2021-en.pdf',
    fileSize: '4.5 MB',
    category: 'sustainability-report',
    year: 2021,
    language: 'en',
    title: 'DPEF / Non-Financial Statement 2021',
    coverImage: ESG_COVER,
  },
  {
    id: 'presentation-fy-2016-17',
    path: '/downloads/fy-2016-17-bondholders-annual-results-presentation-.pdf',
    filename: 'fy-2016-17-bondholders-annual-results-presentation-.pdf',
    fileSize: '3.0 MB',
    category: 'presentation',
    year: 2017,
    language: 'en',
    title: 'FY 2016/17 Bondholders Annual Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'product-brochure-rate016',
    path: '/downloads/rate016-gb-planche-web.pdf',
    filename: 'rate016-gb-planche-web.pdf',
    fileSize: '4.0 MB',
    category: 'catalog',
    year: 2020,
    language: 'en',
    title: 'Product Brochure — Rate 016',
  },
  {
    id: 'product-brochure-rate017',
    path: '/downloads/rate017-gb-web-reduce.pdf',
    filename: 'rate017-gb-web-reduce.pdf',
    fileSize: '4.1 MB',
    category: 'catalog',
    year: 2020,
    language: 'en',
    title: 'Product Brochure — Rate 017',
  },
  {
    id: 'ir-bondholders-2015-16',
    path: '/downloads/2015-16-results---tereos-group---communication-to-bondholders--def1.pdf',
    filename: '2015-16-results---tereos-group---communication-to-bondholders--def1.pdf',
    fileSize: '1.8 MB',
    category: 'ir-document',
    year: 2016,
    language: 'en',
    title: '2015/16 Results — Communication to Bondholders',
    coverImage: IR_COVER,
  },
  {
    id: 'press-annual-results-2018-19',
    path: '/downloads/2019-06-12-cp-rsultats-annuels-tereos-eng-version-longue.pdf',
    filename: '2019-06-12-cp-rsultats-annuels-tereos-eng-version-longue.pdf',
    fileSize: '369 KB',
    category: 'ir-document',
    year: 2019,
    language: 'en',
    title: 'Annual Results 2018/19 — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-avantium-leaf-alliance-2025',
    path: '/downloads/20250923avantiumlvmhandtereosformstrategicalliancetoscalereleafregproductionacrosseurope.pdf',
    filename: '20250923avantiumlvmhandtereosformstrategicalliancetoscalereleafregproductionacrosseurope.pdf',
    fileSize: '182 KB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Avantium, LVMH & Tereos — Releaf Strategic Alliance',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-redemption-notice-2020-01',
    path: '/downloads/cp-en-tereos-pr-redemption-06-january-2020.pdf',
    filename: 'cp-en-tereos-pr-redemption-06-january-2020.pdf',
    fileSize: '145 KB',
    category: 'ir-document',
    year: 2020,
    language: 'en',
    title: 'Bond Redemption Notice — January 2020',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-redemption-notice',
    path: '/downloads/cp-en-tereos-pr-redemption.pdf',
    filename: 'cp-en-tereos-pr-redemption.pdf',
    fileSize: '68 KB',
    category: 'ir-document',
    year: 2019,
    language: 'en',
    title: 'Bond Redemption Notice',
    coverImage: IR_COVER,
  },
  {
    id: 'press-raison-detre-award',
    path: '/downloads/pr-raison-detre-award.pdf',
    filename: 'pr-raison-detre-award.pdf',
    fileSize: '552 KB',
    category: 'ir-document',
    year: 2023,
    language: 'en',
    title: "Raison d'Être Award — Press Release",
    coverImage: IR_COVER,
  },
  {
    id: 'press-brazil-operation',
    path: '/downloads/pr-tereos-brazil-operation.pdf',
    filename: 'pr-tereos-brazil-operation.pdf',
    fileSize: '3.1 MB',
    category: 'ir-document',
    year: 2022,
    language: 'en',
    title: 'Brazil Operations — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-tsoi-operation',
    path: '/downloads/pr-tereos-tsoi-operation.pdf',
    filename: 'pr-tereos-tsoi-operation.pdf',
    fileSize: '467 KB',
    category: 'ir-document',
    year: 2021,
    language: 'en',
    title: 'TSOI Operation — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-outlook-2016-17',
    path: '/downloads/press-release---tereos-increases-its-outlook-for-the-2016-17-financial-year.pdf',
    filename: 'press-release---tereos-increases-its-outlook-for-the-2016-17-financial-year.pdf',
    fileSize: '313 KB',
    category: 'ir-document',
    year: 2017,
    language: 'en',
    title: 'Increased Outlook for FY 2016/17 — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-uk-site-sale-tl-sugars',
    path: '/downloads/press-release-tereos-announces-the-sale-of-its-uk-production-site-to-tl-sugars-limited.pdf',
    filename: 'press-release-tereos-announces-the-sale-of-its-uk-production-site-to-tl-sugars-limited.pdf',
    fileSize: '188 KB',
    category: 'ir-document',
    year: 2024,
    language: 'en',
    title: 'UK Production Site Sale to TL Sugars — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-escaut-river-2023',
    path: '/downloads/press-release-tereos-escaut-river-restoration-october-2023.pdf',
    filename: 'press-release-tereos-escaut-river-restoration-october-2023.pdf',
    fileSize: '211 KB',
    category: 'ir-document',
    year: 2023,
    language: 'en',
    title: 'Escaut River Restoration — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-half-year-2023-24',
    path: '/downloads/press-release-tereos-half-year-results-2023-24-final.pdf',
    filename: 'press-release-tereos-half-year-results-2023-24-final.pdf',
    fileSize: '604 KB',
    category: 'ir-document',
    year: 2024,
    language: 'en',
    title: 'Half-Year Results 2023/24 — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-fret21-scheme',
    path: '/downloads/press-release-tereos-joins-the-fret21-scheme-eng-final.pdf',
    filename: 'press-release-tereos-joins-the-fret21-scheme-eng-final.pdf',
    fileSize: '270 KB',
    category: 'ir-document',
    year: 2022,
    language: 'en',
    title: 'Fret21 Transport Scheme — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-half-year-2024-25-alt',
    path: '/downloads/press-release-tereos-results-halfyear-2024-2025-en.pdf',
    filename: 'press-release-tereos-results-halfyear-2024-2025-en.pdf',
    fileSize: '123 KB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Half-Year Results 2024/25 — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-uk-tl-2024',
    path: '/downloads/press-release-tereos-uk-tl-141024.pdf',
    filename: 'press-release-tereos-uk-tl-141024.pdf',
    fileSize: '259 KB',
    category: 'ir-document',
    year: 2024,
    language: 'en',
    title: 'UK TL Sugars Transaction — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-customer-innovation-centre',
    path: '/downloads/press-release-tereos-unveils-new-customer-innovation-centre.pdf',
    filename: 'press-release-tereos-unveils-new-customer-innovation-centre.pdf',
    fileSize: '157 KB',
    category: 'ir-document',
    year: 2023,
    language: 'en',
    title: 'Customer Innovation Centre — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-futerro-bioplastics',
    path: '/downloads/press-release-tereos-x-futerro-from-wheat-to-bioplastics-final.pdf',
    filename: 'press-release-tereos-x-futerro-from-wheat-to-bioplastics-final.pdf',
    fileSize: '371 KB',
    category: 'ir-document',
    year: 2022,
    language: 'en',
    title: 'Futerro Wheat-to-Bioplastics Partnership — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-natural-products-sale-2025',
    path: '/downloads/release-14042025-tereos-has-sold-its-natural-products-trading-activities-1.pdf',
    filename: 'release-14042025-tereos-has-sold-its-natural-products-trading-activities-1.pdf',
    fileSize: '68 KB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Sale of Natural Products Trading Activities — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-results-2018-19',
    path: '/downloads/results-18-19.pdf',
    filename: 'results-18-19.pdf',
    fileSize: '190 KB',
    category: 'ir-document',
    year: 2019,
    language: 'en',
    title: 'FY 2018/19 Results Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-label-bas-carbone',
    path: '/downloads/tereos--cp-prime-filiere--projet-label-bas-carbone.pdf',
    filename: 'tereos--cp-prime-filiere--projet-label-bas-carbone.pdf',
    fileSize: '283 KB',
    category: 'ir-document',
    year: 2023,
    language: 'en',
    title: 'Label Bas Carbone Project — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-notice-market-2016-10',
    path: '/downloads/tereos-2016-10-12---notice-to-the-market.pdf',
    filename: 'tereos-2016-10-12---notice-to-the-market.pdf',
    fileSize: '57 KB',
    category: 'ir-document',
    year: 2016,
    language: 'en',
    title: 'Notice to the Market — October 2016',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-annual-results-2019-20',
    path: '/downloads/tereos-2019-20-annual-results.pdf',
    filename: 'tereos-2019-20-annual-results.pdf',
    fileSize: '608 KB',
    category: 'ir-document',
    year: 2020,
    language: 'en',
    title: 'Annual Results 2019/20 — Financial Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-annual-results-2020-21',
    path: '/downloads/tereos-2020-21-annual-results-press-release-2021-06-02-eng.pdf',
    filename: 'tereos-2020-21-annual-results-press-release-2021-06-02-eng.pdf',
    fileSize: '487 KB',
    category: 'ir-document',
    year: 2021,
    language: 'en',
    title: 'Annual Results 2020/21 — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-subordinated-securities-issue',
    path: '/downloads/tereos-announces-a-potential-subordinated-perpetual-securities-issue.pdf',
    filename: 'tereos-announces-a-potential-subordinated-perpetual-securities-issue.pdf',
    fileSize: '63 KB',
    category: 'ir-document',
    year: 2020,
    language: 'en',
    title: 'Potential Subordinated Perpetual Securities Issue',
    coverImage: IR_COVER,
  },
  {
    id: 'press-2025-05-28',
    path: '/downloads/tereos-cp-280525-en.pdf',
    filename: 'tereos-cp-280525-en.pdf',
    fileSize: '1.8 MB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Press Release — 28 May 2025',
    coverImage: IR_COVER,
  },
  {
    id: 'financial-statements-2018-19',
    path: '/downloads/tereos-group-audited-consolidated-financial-statements-18-19.pdf',
    filename: 'tereos-group-audited-consolidated-financial-statements-18-19.pdf',
    fileSize: '1023 KB',
    category: 'ir-document',
    year: 2019,
    language: 'en',
    title: 'Audited Consolidated Financial Statements 2018/19',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-financial-release-2019-02',
    path: '/downloads/tereos-group-financial-release-02182019-0.pdf',
    filename: 'tereos-group-financial-release-02182019-0.pdf',
    fileSize: '102 KB',
    category: 'ir-document',
    year: 2019,
    language: 'en',
    title: 'Financial Release — February 2019',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-annual-results-2017-18',
    path: '/downloads/tereos-group-fy-2017-18-annual-results-gb-investor-relations.pdf',
    filename: 'tereos-group-fy-2017-18-annual-results-gb-investor-relations.pdf',
    fileSize: '231 KB',
    category: 'ir-document',
    year: 2018,
    language: 'en',
    title: 'Annual Results 2017/18 — Investor Relations Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-half-year-2016-17',
    path: '/downloads/tereos-group-h1-2016-17-en-investors-relations.pdf',
    filename: 'tereos-group-h1-2016-17-en-investors-relations.pdf',
    fileSize: '149 KB',
    category: 'ir-document',
    year: 2017,
    language: 'en',
    title: 'Half-Year Results 2016/17 — Investor Relations Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-q3-results-2023-24',
    path: '/downloads/tereos-group-results-release-q3-2023-24.pdf',
    filename: 'tereos-group-results-release-q3-2023-24.pdf',
    fileSize: '457 KB',
    category: 'ir-document',
    year: 2024,
    language: 'en',
    title: 'Q3 Results 2023/24 — Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-euroclear-notice-2020-01',
    path: '/downloads/tereos-notice-euroclear-06-january-2020.pdf',
    filename: 'tereos-notice-euroclear-06-january-2020.pdf',
    fileSize: '76 KB',
    category: 'ir-document',
    year: 2020,
    language: 'en',
    title: 'Euroclear Notice — January 2020',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-euroclear-notice',
    path: '/downloads/tereos-notice-euroclear.pdf',
    filename: 'tereos-notice-euroclear.pdf',
    fileSize: '75 KB',
    category: 'ir-document',
    year: 2019,
    language: 'en',
    title: 'Euroclear Notice',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-offer-announcement-2020-10',
    path: '/downloads/tereos-offer-announcement-en-12-oct-2020.pdf',
    filename: 'tereos-offer-announcement-en-12-oct-2020.pdf',
    fileSize: '155 KB',
    category: 'ir-document',
    year: 2020,
    language: 'en',
    title: 'Offer Announcement — October 2020',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-bond-placement-eu400m',
    path: '/downloads/tereos-places-succesffully-a-eu400m-7-year-bond-eng.pdf',
    filename: 'tereos-places-succesffully-a-eu400m-7-year-bond-eng.pdf',
    fileSize: '357 KB',
    category: 'ir-document',
    year: 2016,
    language: 'en',
    title: '€400m 7-Year Bond Placement — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-annual-results-2023-24',
    path: '/downloads/tereos-press-release-2023-24-annual-results.pdf',
    filename: 'tereos-press-release-2023-24-annual-results.pdf',
    fileSize: '572 KB',
    category: 'ir-document',
    year: 2024,
    language: 'en',
    title: 'Annual Results 2023/24 — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'press-ensemble-partnership',
    path: '/downloads/tereos-press-release-ensemble-final.pdf',
    filename: 'tereos-press-release-ensemble-final.pdf',
    fileSize: '258 KB',
    category: 'ir-document',
    year: 2023,
    language: 'en',
    title: 'Ensemble Partnership — Press Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-prospectus-2016',
    path: '/downloads/tereos-prospectus-2016-visa.pdf',
    filename: 'tereos-prospectus-2016-visa.pdf',
    fileSize: '2.4 MB',
    category: 'ir-document',
    year: 2016,
    language: 'en',
    title: 'Bond Prospectus 2016',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-tap-prospectus-2016',
    path: '/downloads/tereos-tap-2016-prospectus-final.pdf',
    filename: 'tereos-tap-2016-prospectus-final.pdf',
    fileSize: '4.4 MB',
    category: 'ir-document',
    year: 2016,
    language: 'en',
    title: 'TAP Prospectus 2016',
    coverImage: IR_COVER,
  },

  // —— Financial information batch (tereos.com finance pages) ——
  {
    id: 'presentation-fy-2025-26',
    path: '/downloads/tereos-presentation-full-year-2025-26-1.pdf',
    filename: 'tereos-presentation-full-year-2025-26-1.pdf',
    fileSize: '2.9 MB',
    category: 'presentation',
    year: 2026,
    language: 'en',
    title: 'Full Year 2025/26 Results Presentation',
    coverImage: IR_COVER,
    featured: true,
  },
  {
    id: 'presentation-h1-2025-26',
    path: '/downloads/tereos-presentation-half-year-2025-26-1.pdf',
    filename: 'tereos-presentation-half-year-2025-26-1.pdf',
    fileSize: '2.9 MB',
    category: 'presentation',
    year: 2025,
    language: 'en',
    title: 'Half-Year 2025/26 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-fy-2024-25',
    path: '/downloads/tereos-presentation-full-year-2024-25-1.pdf',
    filename: 'tereos-presentation-full-year-2024-25-1.pdf',
    fileSize: '2.6 MB',
    category: 'presentation',
    year: 2025,
    language: 'en',
    title: 'Full Year 2024/25 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-h1-2024-25',
    path: '/downloads/tereos-presentation-half-year-2024-25-1.pdf',
    filename: 'tereos-presentation-half-year-2024-25-1.pdf',
    fileSize: '2.6 MB',
    category: 'presentation',
    year: 2024,
    language: 'en',
    title: 'Half-Year 2024/25 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-fy-2023-24',
    path: '/downloads/tereos-presentation-full-year-2023-24.pdf',
    filename: 'tereos-presentation-full-year-2023-24.pdf',
    fileSize: '3.2 MB',
    category: 'presentation',
    year: 2024,
    language: 'en',
    title: 'Full Year 2023/24 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-h1-2023-24',
    path: '/downloads/tereos-presentation-half-year-2023-24-1.pdf',
    filename: 'tereos-presentation-half-year-2023-24-1.pdf',
    fileSize: '2.9 MB',
    category: 'presentation',
    year: 2024,
    language: 'en',
    title: 'Half-Year 2023/24 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-fy-2022-23',
    path: '/downloads/tereos-presentation-full-year-2022-23.pdf',
    filename: 'tereos-presentation-full-year-2022-23.pdf',
    fileSize: '1.2 MB',
    category: 'presentation',
    year: 2023,
    language: 'en',
    title: 'Full Year 2022/23 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-h1-2022-23',
    path: '/downloads/tereos-presentation-half-year-2022-23-1.pdf',
    filename: 'tereos-presentation-half-year-2022-23-1.pdf',
    fileSize: '1.2 MB',
    category: 'presentation',
    year: 2023,
    language: 'en',
    title: 'Half-Year 2022/23 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-fy-2021-22',
    path: '/downloads/tereos-presentation-full-year-2021-22.pdf',
    filename: 'tereos-presentation-full-year-2021-22.pdf',
    fileSize: '1.6 MB',
    category: 'presentation',
    year: 2022,
    language: 'en',
    title: 'Full Year 2021/22 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-fy-2020-21',
    path: '/downloads/tereos-2020-21-annual-results-presentation-2021-06-02-1.pdf',
    filename: 'tereos-2020-21-annual-results-presentation-2021-06-02-1.pdf',
    fileSize: '2.4 MB',
    category: 'presentation',
    year: 2021,
    language: 'en',
    title: 'Full Year 2020/21 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-h1-2020-21',
    path: '/downloads/tereos-h1-2020-21-half-year-results-presentation.pdf',
    filename: 'tereos-h1-2020-21-half-year-results-presentation.pdf',
    fileSize: '2.2 MB',
    category: 'presentation',
    year: 2021,
    language: 'en',
    title: 'Half-Year 2020/21 Results Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-h1-2021-22',
    path: '/downloads/tereos-bondholders-presentation-h1-2021-22.pdf',
    filename: 'tereos-bondholders-presentation-h1-2021-22.pdf',
    fileSize: '2.5 MB',
    category: 'presentation',
    year: 2022,
    language: 'en',
    title: 'H1 2021/22 Bondholders Presentation',
    coverImage: IR_COVER,
  },
  {
    id: 'presentation-press-conference-2021',
    path: '/downloads/tereos-presentation-press-conference-2021-final-version-en.pdf',
    filename: 'tereos-presentation-press-conference-2021-final-version-en.pdf',
    fileSize: '6.6 MB',
    category: 'presentation',
    year: 2021,
    language: 'en',
    title: 'Press Conference Presentation 2021',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-results-release-fy-2025-26',
    path: '/downloads/tereos-group-results-release-fy-2025-26.pdf',
    filename: 'tereos-group-results-release-fy-2025-26.pdf',
    fileSize: '616 KB',
    category: 'ir-document',
    year: 2026,
    language: 'en',
    title: 'Full Year 2025/26 Results Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-results-release-fy-2024-25',
    path: '/downloads/tereos-group-results-release-fy-2024-25.pdf',
    filename: 'tereos-group-results-release-fy-2024-25.pdf',
    fileSize: '545 KB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Full Year 2024/25 Results Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-results-release-h1-2025-26',
    path: '/downloads/tereos-group-results-release-h1-2025-26-en.pdf',
    filename: 'tereos-group-results-release-h1-2025-26-en.pdf',
    fileSize: '515 KB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Half-Year 2025/26 Results Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-results-release-q1-2025-26',
    path: '/downloads/tereos-group-results-release-q1-2025-26.pdf',
    filename: 'tereos-group-results-release-q1-2025-26.pdf',
    fileSize: '529 KB',
    category: 'ir-document',
    year: 2026,
    language: 'en',
    title: 'Q1 2025/26 Results Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-results-release-q3-2025-26',
    path: '/downloads/tereos-group-results-release-q3-2025-26.pdf',
    filename: 'tereos-group-results-release-q3-2025-26.pdf',
    fileSize: '506 KB',
    category: 'ir-document',
    year: 2026,
    language: 'en',
    title: 'Q3 2025/26 Results Release',
    coverImage: IR_COVER,
  },
  {
    id: 'ir-results-release-q3-2024-25',
    path: '/downloads/tereos-group-results-release-q3-2024-25.pdf',
    filename: 'tereos-group-results-release-q3-2024-25.pdf',
    fileSize: '422 KB',
    category: 'ir-document',
    year: 2024,
    language: 'en',
    title: 'Q3 2024/25 Results Release',
    coverImage: IR_COVER,
  },
  {
    id: 'financial-statements-fy-2025-26-en',
    path: '/downloads/consolidated-financial-statements-full-year-25-26-eng-1.pdf',
    filename: 'consolidated-financial-statements-full-year-25-26-eng-1.pdf',
    fileSize: '1.7 MB',
    category: 'ir-document',
    year: 2026,
    language: 'en',
    title: 'Consolidated Financial Statements FY 2025/26 (English)',
    coverImage: IR_COVER,
  },
  {
    id: 'financial-statements-fy-2025-26-fr',
    path: '/downloads/consolidated-financial-statements-full-year-25-26-fra.pdf',
    filename: 'consolidated-financial-statements-full-year-25-26-fra.pdf',
    fileSize: '2.0 MB',
    category: 'ir-document',
    year: 2026,
    language: 'all',
    title: 'Consolidated Financial Statements FY 2025/26 (French)',
    coverImage: IR_COVER,
  },
  {
    id: 'financial-statements-h1-2025-26-en',
    path: '/downloads/consolidated-financial-statements-half-year-h1-25-26-eng.pdf',
    filename: 'consolidated-financial-statements-half-year-h1-25-26-eng.pdf',
    fileSize: '990 KB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Consolidated Financial Statements H1 2025/26 (English)',
    coverImage: IR_COVER,
  },
  {
    id: 'financial-statements-fy-2024-25-en',
    path: '/downloads/consolidated-financial-statements-full-year-24-25-eng.pdf',
    filename: 'consolidated-financial-statements-full-year-24-25-eng.pdf',
    fileSize: '856 KB',
    category: 'ir-document',
    year: 2025,
    language: 'en',
    title: 'Consolidated Financial Statements FY 2024/25 (English)',
    coverImage: IR_COVER,
  },
  {
    id: 'corporate-update-jan-2025',
    path: '/downloads/tereos-update-january-2025-1.pdf',
    filename: 'tereos-update-january-2025-1.pdf',
    fileSize: '3.7 MB',
    category: 'presentation',
    year: 2025,
    language: 'en',
    title: 'Tereos Update — January 2025',
    coverImage: IR_COVER,
  },
  {
    id: 'corporate-update-jan-2026',
    path: '/downloads/tereos-update-january-2026.pdf',
    filename: 'tereos-update-january-2026.pdf',
    fileSize: '3.5 MB',
    category: 'presentation',
    year: 2026,
    language: 'en',
    title: 'Tereos Update — January 2026',
    coverImage: IR_COVER,
  },
  {
    id: 'corporate-update-mar-2025',
    path: '/downloads/tereos-update-march-2025.pdf',
    filename: 'tereos-update-march-2025.pdf',
    fileSize: '2.8 MB',
    category: 'presentation',
    year: 2025,
    language: 'en',
    title: 'Tereos Update — March 2025',
    coverImage: IR_COVER,
  },
  {
    id: 'corporate-update-sep-2025',
    path: '/downloads/tereos-update-september-2025-1.pdf',
    filename: 'tereos-update-september-2025-1.pdf',
    fileSize: '2.7 MB',
    category: 'presentation',
    year: 2025,
    language: 'en',
    title: 'Tereos Update — September 2025',
    coverImage: IR_COVER,
  },
  {
    id: 'disclosure-document-jan-2026',
    path: '/downloads/disclosure-document-12-jan-2026.pdf',
    filename: 'disclosure-document-12-jan-2026.pdf',
    fileSize: '2.3 MB',
    category: 'ir-document',
    year: 2026,
    language: 'en',
    title: 'Disclosure Document — January 2026',
    coverImage: IR_COVER,
  },
];

const assetById = new Map(DOCUMENT_ASSETS.map((asset) => [asset.id, asset]));

export function getDocumentAsset(id: string): DocumentAsset | undefined {
  return assetById.get(id);
}

export function getDocumentFileUrl(id: string): string {
  return getDocumentAsset(id)?.path ?? '#';
}

export function buildDownloadDocument(asset: DocumentAsset, id?: string): DownloadDocument {
  return enrichDownloadDocument({
    id: id ?? asset.id,
    title: asset.title,
    fileUrl: asset.path,
    category: asset.category,
    language: asset.language,
    year: asset.year,
    fileSize: asset.fileSize,
    coverImage: asset.coverImage,
    gated: asset.gated,
  });
}

/** Fallback library for download center, IR, and newsroom documents tab */
export function getFallbackDownloadDocuments(): DownloadDocument[] {
  return [...DOCUMENT_ASSETS]
    .sort((a, b) => b.year - a.year || a.title.localeCompare(b.title))
    .map((asset) => buildDownloadDocument(asset));
}

/** Press release slug → document registry id */
export const PRESS_RELEASE_PDF_MAP: Record<string, string> = {
  'bioenergy-expansion-sea': 'press-saf-2026',
  'q1-results-2026': 'ir-results-release-q1-2025-26',
  'sustainability-report-2025': 'non-financial-statement-2024-25',
};

export function getPressReleasePdfUrl(slug: string): string | undefined {
  const key = PRESS_RELEASE_PDF_MAP[slug];
  if (!key) return undefined;
  const url = getDocumentFileUrl(key);
  return url === '#' ? undefined : url;
}

/** Sustainability page report cards */
export const SUSTAINABILITY_REPORT_LINKS = [
  { documentId: 'non-financial-statement-2024-25', title: 'Non-Financial Statement 2024/25', year: 2025 },
  { documentId: 'sustainability-report-2024', title: 'Sustainability Report 2024', year: 2024 },
  { documentId: 'ethical-charter-2025', title: 'Ethical Charter 2025', year: 2025 },
  { documentId: 'sustain-2030-leaflet', title: "SUSTAIN'2030 CSR Roadmap", year: 2025 },
  { documentId: 'quality-charter-2023', title: 'Quality Charter 2023', year: 2023 },
] as const;

/** Count of PDFs in folder vs registered (for dev reference) */
export const REGISTERED_DOWNLOAD_COUNT = DOCUMENT_ASSETS.length;
